# Generated by Django 3.0.6 on 2020-05-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='updateCorona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Index', models.CharField(max_length=128)),
                ('Country_Name', models.CharField(max_length=128)),
                ('Total_Cases', models.CharField(max_length=128)),
                ('New_Cases', models.CharField(max_length=128)),
                ('Deaths_Per_Country', models.CharField(max_length=128)),
                ('New_Death', models.CharField(max_length=128)),
                ('Total_Recovered', models.CharField(max_length=128)),
                ('Active_Cases', models.CharField(max_length=128)),
                ('Serious_and_Critical', models.CharField(max_length=128)),
                ('Cases_Per_Million', models.CharField(max_length=128)),
                ('Death_Per_Millions', models.CharField(max_length=128)),
                ('Total_Tests', models.CharField(max_length=128)),
                ('Tests_Per_Millions', models.CharField(max_length=128)),
                ('Total_Population', models.CharField(max_length=128)),
            ],
        ),
    ]
