# Generated by Django 3.0.6 on 2020-05-29 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscrap', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='updateCorona',
            new_name='Coronacases',
        ),
    ]
